// Stub for Globals class which is usually generated by VSTO
namespace OutlookOkan
{
    internal static class Globals
    {
        private static ThisAddIn _thisAddIn;

        internal static ThisAddIn ThisAddIn
        {
            get
            {
                if (_thisAddIn == null)
                {
                    _thisAddIn = new ThisAddIn();
                }
                return _thisAddIn;
            }
            set { _thisAddIn = value; }
        }

        internal static Microsoft.Office.Tools.Outlook.Factory Factory { get; set; }
        internal static Ribbon Ribbon { get; set; }
    }
}

namespace Microsoft.Office.Tools.Outlook
{
    public interface Factory
    {
        Microsoft.Office.Tools.Ribbon.RibbonFactory GetRibbonFactory();
    }
}

namespace Microsoft.Office.Tools.Ribbon
{
    public interface RibbonFactory
    {
    }
}
